### ISSUE TITLE
The .cfg file for the YOLO weights

### ISSUE THREAD

**Issue by njanirudh** [MiguelARD/DoorDetect_Dataset#1]
I am trying to use the YOLO weights gives along with OpenCV and I also required the '.cfg' file.
I tried the YOLOv3 .cfg file given here(https://pjreddie.com/darknet/yolo/) but it dosnt seem to work.

Can you specify which YOLO version is the weights based on and if possible share the .cfg file.

**Comment by MiguelARD** [comment]
My apologies for the late response. The .cfg file is already uploaded in the repository.
